on:
  workflow_dispatch:
  push:
env:
  INPUT_OWNER: kabir
  INPUT_REPO: openshift-sanity-test
  INPUT_TOKEN: ${{ secrets.REMOTE_DISPATCH_TOKEN }}
  INPUT_EVENT_TYPE: trigger-cloud-tests-run
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo ${GITHUB_CONTEXT}
          
      - name: Output Job
        env:
          JOB_CONTEXT: ${{toJson(job)}}
        run: |
          echo ${JOB_CONTEXT}
          
      - name: Output Env
        env:
          ENV_CONTEXT: ${{toJson(env)}}
        run: |
          echo ${ENV_CONTEXT}
          
      - name: Remote Dispatch
    
        run: |
          echo $GITHUB_REPOSITORY
          
          #INPUT_CLIENT_PAYLOAD='{\"triggerRepo\" : "$GITHUB_REPOSITORY", "ref" : "$GITHUB_REF", "triggerWorkflowRunId" : "$GITHUB_RUN_ID"}'
          #INPUT_CLIENT_PAYLOAD='{\"triggerRepo\" : "$GITHUB_REPOSITORY"}'

          #echo "INPUT_CLIENT_PAYLOAD:"
          #echo "$INPUT_CLIENT_PAYLOAD"

          INPUT_CLIENT_PAYLOAD=$( jq -n \
                  --arg tr "$GITHUB_REPOSITORY" \
                  --arg ref "$GITHUB_REF" \
                  --arg twrid "$GITHUB_RUN_ID" \
                  '{triggerRepo: $tr, ref: $ref, triggerWorkflowRunId: $twrid}' )

          echo "INPUT_CLIENT_PAYLOAD:"
          echo "$INPUT_CLIENT_PAYLOAD"


          resp=$(curl -X POST -s "https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${INPUT_TOKEN}" \
              -d "{\"event_type\": \"${INPUT_EVENT_TYPE}\", \"client_payload\": ${INPUT_CLIENT_PAYLOAD} }")

          if [ -z "$resp" ]
          then
            sleep 2
          else
            echo "Workflow failed to trigger"
            echo "$resp"
            exit 1
          fi
