on:
  workflow_dispatch:
  push:
env:
  INPUT_OWNER: kabir
  INPUT_REPO: openshift-sanity-test
  INPUT_TOKEN: ${{ secrets.REMOTE_DISPATCH_TOKEN }}
  INPUT_EVENT_TYPE: trigger_run
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event
        run: |
          echo toJSON(${{ github.event}}) 
          
      - name: Remote Dispatch
        run: |
          
          
          INPUT_CLIENT_PAYLOAD='{"triggerRepo" : "$GITHUB_REPOSITORY", "ref" : "$GITHUB_REF", "triggerWorkflowRunId" : "$GITHUB_REF"}'

          echo "INPUT_CLIENT_PAYLOAD:"
          echo "$INPUT_CLIENT_PAYLOAD"


          resp=$(curl -X POST -s "https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${INPUT_TOKEN}" \
              -d "{\"event_type\": \"${INPUT_EVENT_TYPE}\", \"client_payload\": ${INPUT_CLIENT_PAYLOAD} }")

          if [ -z "$resp" ]
          then
            sleep 2
          else
            echo "Workflow failed to trigger"
            echo "$resp"
            exit 1
          fi
