on:
  workflow_dispatch:
  push:
env:
  REPOSITORY: kabir/openshift-sanity-test
  REPO: openshift-sanity-test
  STATUS_BRANCH: run-status
  TOKEN: ${{ secrets.REMOTE_DISPATCH_TOKEN }}
  EVENT_TYPE: trigger-cloud-tests-run
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
#       - name: Output GitHub
#         env:
#           GITHUB_CONTEXT: ${{toJson(github)}}
#         run: |
#           echo ${GITHUB_CONTEXT}
      
      - name: Checkout run-status branch
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPOSITORY }}
          ref: run-status
          
      - name: Remote Dispatch    
        run: |
          echo $GITHUB_REPOSITORY
          
          #CLIENT_PAYLOAD='{\"triggerRepo\" : "$GITHUB_REPOSITORY", "ref" : "$GITHUB_REF", "triggerWorkflowRunId" : "$GITHUB_RUN_ID"}'
          #CLIENT_PAYLOAD='{\"triggerRepo\" : "$GITHUB_REPOSITORY"}'

          #echo "CLIENT_PAYLOAD:"
          #echo "$CLIENT_PAYLOAD"

          CLIENT_PAYLOAD=$( jq -n \
                  --arg tr "$GITHUB_REPOSITORY" \
                  --arg ref "$GITHUB_REF" \
                  --arg twrid "$GITHUB_RUN_ID" \
                  --arg twrno "$GITHUB_RUN_NUMBER" \
                  '{triggerRepo: $tr, ref: $ref, triggerWorkflowRunId: $twrid, triggerWorkflowRunNumber: $twrno}' )

          echo "CLIENT_PAYLOAD:"
          echo "$CLIENT_PAYLOAD"


          resp=$(curl -X POST -s "https://api.github.com/repos/${REPOSITORY}/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${TOKEN}" \
              -d "{\"event_type\": \"${EVENT_TYPE}\", \"client_payload\": ${CLIENT_PAYLOAD} }")

          if [ -z "$resp" ]
          then
            sleep 2
          else
            echo "Workflow failed to trigger"
            echo "$resp"
            exit 1
          fi
          
#       - name: Temp Sleep
#         run: |
#           echo "Sleeping 120s..."
#           sleep 120
#           echo "Woke up!"
